all:
  children:
    hyperv_nodes:
      hosts:
        hvparis01.contoso.local:
        hvparis02.contoso.local:
        hvlyon01.contoso.local:
    scvmm_servers:
      hosts:
        scvmm01.contoso.local:
